name: CI

env:
  POETRY_VIRTUALENVS_IN_PROJECT: true

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    types: [opened, synchronize]
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: pipx install poetry

      - uses: actions/setup-python@v4
        id: py
        with:
          python-version: 3.11
          cache: poetry

      - run: poetry install --no-interaction

      - run: poetry run black . --check

      - run: poetry run ruff check .

      - run: poetry run pytest
