name: Scrape

env:
  POETRY_VIRTUALENVS_IN_PROJECT: true
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  SUPABASE_TABLE: ${{ vars.SUPABASE_TABLE }}
  SCRAPY_SETTINGS_MODULE: tracker.settings.prod

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: "11 7 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        scraper:
          - city_council
          - bseed_permits
          - brownfield
          - planning_commission
          - bseed_special
          - community_benefits
          - historic_district_commission
          - medc_incentives
          - state_tax_exemptions
          - state_tax_nez
          - medc_programs
          - board_zoning_appeals
          - det_press_releases

    steps:
      - uses: actions/checkout@v2

      - run: pipx install poetry

      - uses: actions/setup-python@v4
        id: py
        with:
          python-version: 3.11
          cache: poetry

      - run: poetry install --no-interaction

      - name: Install playwright if needed
        if: matrix.scraper == 'city_council'
        run: |
          poetry run playwright install

      - name: Run scraper ${{ matrix.scraper }}
        run: |
          export PYTHONPATH=$(pwd):$PYTHONPATH
          poetry run scrapy crawl ${{ matrix.scraper }}
