name: Scrape

env:
  POETRY_VIRTUALENVS_IN_PROJECT: true
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  SUPABASE_TABLE: ${{ vars.SUPABASE_TABLE }}
  SCRAPY_SETTINGS_MODULE: tracker.settings.prod

permissions:
  id-token: write
  contents: read

on:
  # cron:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scraper:
          - city_council
          - bseed_permits
          - brownfield

    steps:
      - uses: actions/checkout@v2

      - run: pipx install poetry

      - uses: actions/setup-python@v4
        id: py
        with:
          python-version: 3.11
          cache: poetry

      - run: poetry install --no-interaction

      - run: poetry run scrapy crawl ${{ matrix.scraper }}
